name: publish

on:
  release:
    types: [created]

jobs:
  build-and-publish:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.x]

    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        make install

    - name: Format with black
      run: |
        make format-check

    - name: Import sorting with isort
      run: |
        make isort-check

    - name: Lint with flake8
      run: |
        make lint

    - name: Static check with mypy
      run: |
        make mypy

    - name: Test with pytest
      run: |
        make test

    - name: Build package
      run: |
        pip3 install wheel
        pip3 install setuptools
        make dist wheel

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip-existing: true
